apiVersion: kubernetes.vault.upbound.io/v1alpha1
kind: SecretBackendRole
metadata:
  annotations:
    meta.upbound.io/example-id: kubernetes/v1alpha1/secretbackendrole
  labels:
    testing.upbound.io/example-name: sa-example
  name: sa-example
spec:
  forProvider:
    allowedKubernetesNamespaces:
    - '*'
    backendSelector:
      matchLabels:
        testing.upbound.io/example-name: config
    extraAnnotations:
      env: development
      location: earth
    extraLabels:
      id: abc123
      name: some_name
    name: service-account-name-role
    serviceAccountName: test-service-account-with-generated-token
    tokenDefaultTtl: 21600
    tokenMaxTtl: 43200

---

apiVersion: kubernetes.vault.upbound.io/v1alpha1
kind: SecretBackend
metadata:
  annotations:
    meta.upbound.io/example-id: kubernetes/v1alpha1/secretbackendrole
  labels:
    testing.upbound.io/example-name: config
  name: config
spec:
  forProvider:
    description: kubernetes secrets engine description
    disableLocalCaJwt: false
    kubernetesCaCert: ${file("/path/to/cert")}
    kubernetesHost: https://127.0.0.1:61233
    path: kubernetes
    serviceAccountJwtSecretRef:
      key: attribute.token
      name: example-secret
      namespace: upbound-system
