apiVersion: rabbitmq.vault.upbound.io/v1alpha1
kind: SecretBackend
metadata:
  annotations:
    meta.upbound.io/example-id: rabbitmq/v1alpha1/secretbackend
  labels:
    testing.upbound.io/example-name: rabbitmq
  name: rabbitmq
spec:
  forProvider:
    connectionUri: https://.....
    passwordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    usernameSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
