apiVersion: nomad.vault.upbound.io/v1alpha1
kind: SecretBackend
metadata:
  annotations:
    meta.upbound.io/example-id: nomad/v1alpha1/secretbackend
  labels:
    testing.upbound.io/example-name: config
  name: config
spec:
  forProvider:
    address: https://127.0.0.1:4646
    backend: nomad
    defaultLeaseTtlSeconds: "3600"
    description: test description
    maxLeaseTtlSeconds: "7200"
    maxTtl: "240"
    tokenSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    ttl: "120"
