apiVersion: gcp.vault.upbound.io/v1alpha1
kind: SecretStaticAccount
metadata:
  annotations:
    meta.upbound.io/example-id: gcp/v1alpha1/secretstaticaccount
  labels:
    testing.upbound.io/example-name: static_account
  name: static-account
spec:
  forProvider:
    backendSelector:
      matchLabels:
        testing.upbound.io/example-name: gcp
    binding:
    - resource: //cloudresourcemanager.googleapis.com/projects/${google_service_account.this.project}
      roles:
      - roles/viewer
    secretType: access_token
    serviceAccountEmail: ${google_service_account.this.email}
    staticAccount: project_viewer
    tokenScopes:
    - https://www.googleapis.com/auth/cloud-platform

---

apiVersion: gcp.vault.upbound.io/v1alpha1
kind: SecretBackend
metadata:
  annotations:
    meta.upbound.io/example-id: gcp/v1alpha1/secretstaticaccount
  labels:
    testing.upbound.io/example-name: gcp
  name: gcp
spec:
  forProvider:
    credentialsSecretRef:
      key: attribute.credentials.json
      name: example-secret
      namespace: upbound-system
    path: gcp
