apiVersion: gcp.vault.upbound.io/v1alpha1
kind: SecretRoleset
metadata:
  annotations:
    meta.upbound.io/example-id: gcp/v1alpha1/secretroleset
  labels:
    testing.upbound.io/example-name: roleset
  name: roleset
spec:
  forProvider:
    backendSelector:
      matchLabels:
        testing.upbound.io/example-name: gcp
    binding:
    - resource: //cloudresourcemanager.googleapis.com/projects/${local.project}
      roles:
      - roles/viewer
    project: ${local.project}
    roleset: project_viewer
    secretType: access_token
    tokenScopes:
    - https://www.googleapis.com/auth/cloud-platform

---

apiVersion: gcp.vault.upbound.io/v1alpha1
kind: SecretBackend
metadata:
  annotations:
    meta.upbound.io/example-id: gcp/v1alpha1/secretroleset
  labels:
    testing.upbound.io/example-name: gcp
  name: gcp
spec:
  forProvider:
    credentialsSecretRef:
      key: attribute.credentials.json
      name: example-secret
      namespace: upbound-system
    path: gcp
