apiVersion: transit.vault.upbound.io/v1alpha1
kind: SecretBackendKey
metadata:
  annotations:
    meta.upbound.io/example-id: transit/v1alpha1/secretbackendkey
  labels:
    testing.upbound.io/example-name: key
  name: key
spec:
  forProvider:
    backendSelector:
      matchLabels:
        testing.upbound.io/example-name: transit
    name: my_key

---

apiVersion: vault.vault.upbound.io/v1alpha1
kind: Mount
metadata:
  annotations:
    meta.upbound.io/example-id: transit/v1alpha1/secretbackendkey
  labels:
    testing.upbound.io/example-name: transit
  name: transit
spec:
  forProvider:
    defaultLeaseTtlSeconds: 3600
    description: Example description
    maxLeaseTtlSeconds: 86400
    path: transit
    type: transit
