apiVersion: identity.vault.upbound.io/v1alpha1
kind: MfaDuo
metadata:
  annotations:
    meta.upbound.io/example-id: identity/v1alpha1/mfaduo
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    apiHostname: api-xxxxxxxx.duosecurity.com
    integrationKeySecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    secretKeySecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
