apiVersion: raft.vault.upbound.io/v1beta1
kind: Autopilot
metadata:
  annotations:
    meta.upbound.io/example-id: raft/v1beta1/autopilot
  labels:
    testing.upbound.io/example-name: autopilot
  name: autopilot
spec:
  forProvider:
    cleanupDeadServers: true
    deadServerLastContactThreshold: 24h0m0s
    lastContactThreshold: 10s
    maxTrailingLogs: 1000
    minQuorum: 3
    serverStabilizationTime: 10s
