apiVersion: vault.upbound.io/v1alpha1
kind: StoreConfig
metadata:
  name: vault
spec:
  type: Vault
  defaultScope: upbound-system
  vault:
    server: http://vault.vault-system:8200
    mountPath: kv2/
    version: v2
    auth:
      method: Token
      token:
        source: Secret
        secretRef:
          namespace: upbound-system
          name: vault-token
          key: token
