apiVersion: token.vault.upbound.io/v1beta1
kind: AuthBackendRole
metadata:
  annotations:
    meta.upbound.io/example-id: token/v1beta1/authbackendrole
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    allowedEntityAliases:
    - test_entity
    allowedPolicies:
    - dev
    - test
    disallowedPolicies:
    - default
    orphan: true
    pathSuffix: path-suffix
    renewable: true
    roleName: my-role
    tokenExplicitMaxTtl: "115200"
    tokenPeriod: "86400"
