/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type GroupMemberEntityIdsInitParameters struct {

	// Defaults to true.
	// If set to true, allows the resource to manage member entity ids
	// exclusively. Beware of race conditions when disabling exclusive management
	Exclusive *bool `json:"exclusive,omitempty" tf:"exclusive,omitempty"`

	// Group ID to assign member entities to.
	// ID of the group.
	// +crossplane:generate:reference:type=github.com/upbound/provider-vault/apis/identity/v1alpha1.Group
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractResourceID()
	GroupID *string `json:"groupId,omitempty" tf:"group_id,omitempty"`

	// Reference to a Group in identity to populate groupId.
	// +kubebuilder:validation:Optional
	GroupIDRef *v1.Reference `json:"groupIdRef,omitempty" tf:"-"`

	// Selector for a Group in identity to populate groupId.
	// +kubebuilder:validation:Optional
	GroupIDSelector *v1.Selector `json:"groupIdSelector,omitempty" tf:"-"`

	// List of member entities that belong to the group
	// Entity IDs to be assigned as group members.
	// +listType=set
	MemberEntityIds []*string `json:"memberEntityIds,omitempty" tf:"member_entity_ids,omitempty"`

	// The namespace to provision the resource in.
	// The value should not contain leading or trailing forward slashes.
	// The namespace is always relative to the provider's configured namespace.
	// Available only for Vault Enterprise.
	// Target namespace. (requires Enterprise)
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`
}

type GroupMemberEntityIdsObservation struct {

	// Defaults to true.
	// If set to true, allows the resource to manage member entity ids
	// exclusively. Beware of race conditions when disabling exclusive management
	Exclusive *bool `json:"exclusive,omitempty" tf:"exclusive,omitempty"`

	// Group ID to assign member entities to.
	// ID of the group.
	GroupID *string `json:"groupId,omitempty" tf:"group_id,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// List of member entities that belong to the group
	// Entity IDs to be assigned as group members.
	// +listType=set
	MemberEntityIds []*string `json:"memberEntityIds,omitempty" tf:"member_entity_ids,omitempty"`

	// The namespace to provision the resource in.
	// The value should not contain leading or trailing forward slashes.
	// The namespace is always relative to the provider's configured namespace.
	// Available only for Vault Enterprise.
	// Target namespace. (requires Enterprise)
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`
}

type GroupMemberEntityIdsParameters struct {

	// Defaults to true.
	// If set to true, allows the resource to manage member entity ids
	// exclusively. Beware of race conditions when disabling exclusive management
	// +kubebuilder:validation:Optional
	Exclusive *bool `json:"exclusive,omitempty" tf:"exclusive,omitempty"`

	// Group ID to assign member entities to.
	// ID of the group.
	// +crossplane:generate:reference:type=github.com/upbound/provider-vault/apis/identity/v1alpha1.Group
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	GroupID *string `json:"groupId,omitempty" tf:"group_id,omitempty"`

	// Reference to a Group in identity to populate groupId.
	// +kubebuilder:validation:Optional
	GroupIDRef *v1.Reference `json:"groupIdRef,omitempty" tf:"-"`

	// Selector for a Group in identity to populate groupId.
	// +kubebuilder:validation:Optional
	GroupIDSelector *v1.Selector `json:"groupIdSelector,omitempty" tf:"-"`

	// List of member entities that belong to the group
	// Entity IDs to be assigned as group members.
	// +kubebuilder:validation:Optional
	// +listType=set
	MemberEntityIds []*string `json:"memberEntityIds,omitempty" tf:"member_entity_ids,omitempty"`

	// The namespace to provision the resource in.
	// The value should not contain leading or trailing forward slashes.
	// The namespace is always relative to the provider's configured namespace.
	// Available only for Vault Enterprise.
	// Target namespace. (requires Enterprise)
	// +kubebuilder:validation:Optional
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`
}

// GroupMemberEntityIdsSpec defines the desired state of GroupMemberEntityIds
type GroupMemberEntityIdsSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     GroupMemberEntityIdsParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider GroupMemberEntityIdsInitParameters `json:"initProvider,omitempty"`
}

// GroupMemberEntityIdsStatus defines the observed state of GroupMemberEntityIds.
type GroupMemberEntityIdsStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        GroupMemberEntityIdsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// GroupMemberEntityIds is the Schema for the GroupMemberEntityIdss API. Manages member entities for an Identity Group for Vault.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vault}
type GroupMemberEntityIds struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              GroupMemberEntityIdsSpec   `json:"spec"`
	Status            GroupMemberEntityIdsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// GroupMemberEntityIdsList contains a list of GroupMemberEntityIdss
type GroupMemberEntityIdsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []GroupMemberEntityIds `json:"items"`
}

// Repository type metadata.
var (
	GroupMemberEntityIds_Kind             = "GroupMemberEntityIds"
	GroupMemberEntityIds_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: GroupMemberEntityIds_Kind}.String()
	GroupMemberEntityIds_KindAPIVersion   = GroupMemberEntityIds_Kind + "." + CRDGroupVersion.String()
	GroupMemberEntityIds_GroupVersionKind = CRDGroupVersion.WithKind(GroupMemberEntityIds_Kind)
)

func init() {
	SchemeBuilder.Register(&GroupMemberEntityIds{}, &GroupMemberEntityIdsList{})
}
