apiVersion: password.vault.upbound.io/v1alpha1
kind: Policy
metadata:
  name: example-password-policy
spec:
  forProvider:
    name: example-password-policy
    policy: |
      length = 20
      rule "charset" {
        charset = "abcdefghijklmnopqrstuvwxyz"
        min-chars = 1
      }
      rule "charset" {
        charset = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
        min-chars = 1
      }
      rule "charset" {
        charset = "0123456789"
        min-chars = 1
      }
      rule "charset" {
        charset = "!@#$%^&*()-_=+[]{}|;:,.<>?"
        min-chars = 1
      }
  providerConfigRef:
    name: vault-provider-config