/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type AuthBackendUserInitParameters struct {
	Backend *string `json:"backend,omitempty" tf:"backend,omitempty"`

	Groups []*string `json:"groups,omitempty" tf:"groups,omitempty"`

	// Target namespace. (requires Enterprise)
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	Policies []*string `json:"policies,omitempty" tf:"policies,omitempty"`

	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type AuthBackendUserObservation struct {
	Backend *string `json:"backend,omitempty" tf:"backend,omitempty"`

	Groups []*string `json:"groups,omitempty" tf:"groups,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Target namespace. (requires Enterprise)
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	Policies []*string `json:"policies,omitempty" tf:"policies,omitempty"`

	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type AuthBackendUserParameters struct {

	// +kubebuilder:validation:Optional
	Backend *string `json:"backend,omitempty" tf:"backend,omitempty"`

	// +kubebuilder:validation:Optional
	Groups []*string `json:"groups,omitempty" tf:"groups,omitempty"`

	// Target namespace. (requires Enterprise)
	// +kubebuilder:validation:Optional
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// +kubebuilder:validation:Optional
	Policies []*string `json:"policies,omitempty" tf:"policies,omitempty"`

	// +kubebuilder:validation:Optional
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

// AuthBackendUserSpec defines the desired state of AuthBackendUser
type AuthBackendUserSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     AuthBackendUserParameters `json:"forProvider"`
	// THIS IS AN ALPHA FIELD. Do not use it in production. It is not honored
	// unless the relevant Crossplane feature flag is enabled, and may be
	// changed or removed without notice.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AuthBackendUserInitParameters `json:"initProvider,omitempty"`
}

// AuthBackendUserStatus defines the observed state of AuthBackendUser.
type AuthBackendUserStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AuthBackendUserObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// AuthBackendUser is the Schema for the AuthBackendUsers API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vault}
type AuthBackendUser struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.username) || has(self.initProvider.username)",message="username is a required parameter"
	Spec   AuthBackendUserSpec   `json:"spec"`
	Status AuthBackendUserStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AuthBackendUserList contains a list of AuthBackendUsers
type AuthBackendUserList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AuthBackendUser `json:"items"`
}

// Repository type metadata.
var (
	AuthBackendUser_Kind             = "AuthBackendUser"
	AuthBackendUser_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AuthBackendUser_Kind}.String()
	AuthBackendUser_KindAPIVersion   = AuthBackendUser_Kind + "." + CRDGroupVersion.String()
	AuthBackendUser_GroupVersionKind = CRDGroupVersion.WithKind(AuthBackendUser_Kind)
)

func init() {
	SchemeBuilder.Register(&AuthBackendUser{}, &AuthBackendUserList{})
}
