apiVersion: aws.vault.upbound.io/v1alpha1
kind: SecretBackend
metadata:
  annotations:
    meta.upbound.io/example-id: aws/v1alpha1/secretbackend
  labels:
    testing.upbound.io/example-name: aws
  name: aws
spec:
  forProvider:
    accessKeySecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    secretKeySecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
