apiVersion: kv.vault.upbound.io/v1alpha1
kind: Secret
metadata:
  annotations:
    meta.upbound.io/example-id: kv/v1alpha1/secret
  labels:
    testing.upbound.io/example-name: vault-creds
  name: vault-creds
spec:
  forProvider:
    path: "kvv1/vault-creds"
    dataJsonSecretRef:
      name: vault-creds
      namespace: vault
      key: credentials
  providerConfigRef:
    name: vault-provider-config
---
apiVersion: vault.vault.upbound.io/v1alpha1
kind: Mount
metadata:
  annotations:
    meta.upbound.io/example-id: kv/v1alpha1/secret
  labels:
    testing.upbound.io/example-name: vault-creds
  name: vault-creds-kv1
spec:
  deletionPolicy: Delete
  forProvider:
    path: "kvv1"
    type: "kv-v1"
  providerConfigRef:
    name: vault-provider-config
