apiVersion: ad.vault.upbound.io/v1alpha1
kind: SecretRole
metadata:
  annotations:
    meta.upbound.io/example-id: ad/v1alpha1/secretrole
  labels:
    testing.upbound.io/example-name: role
  name: role
spec:
  forProvider:
    backendSelector:
      matchLabels:
        testing.upbound.io/example-name: config
    role: bob
    serviceAccountName: Bob
    ttl: 60

---

apiVersion: ad.vault.upbound.io/v1alpha1
kind: SecretBackend
metadata:
  annotations:
    meta.upbound.io/example-id: ad/v1alpha1/secretrole
  labels:
    testing.upbound.io/example-name: config
  name: config
spec:
  forProvider:
    backend: ad
    binddn: CN=Administrator,CN=Users,DC=corp,DC=example,DC=net
    bindpassSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    insecureTls: "true"
    url: ldaps://ad
    userdn: CN=Users,DC=corp,DC=example,DC=net
