apiVersion: transform.vault.upbound.io/v1beta1
kind: Alphabet
metadata:
  annotations:
    meta.upbound.io/example-id: transform/v1beta1/alphabet
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    alphabet: "0123456789"
    name: numerics
    pathSelector:
      matchLabels:
        testing.upbound.io/example-name: mount_transform

---

apiVersion: vault.vault.upbound.io/v1beta1
kind: Mount
metadata:
  annotations:
    meta.upbound.io/example-id: transform/v1beta1/alphabet
  labels:
    testing.upbound.io/example-name: mount_transform
  name: mount-transform
spec:
  forProvider:
    path: transform
    type: transform
