apiVersion: transform.vault.upbound.io/v1beta1
kind: Transformation
metadata:
  annotations:
    meta.upbound.io/example-id: transform/v1beta1/transformation
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    allowedRoles:
    - payments
    name: ccn-fpe
    pathSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    template: ccn
    tweakSource: internal
    type: fpe

---

apiVersion: vault.vault.upbound.io/v1beta1
kind: Mount
metadata:
  annotations:
    meta.upbound.io/example-id: transform/v1beta1/transformation
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    path: transform
    type: transform
