apiVersion: pki.vault.upbound.io/v1beta1
kind: SecretBackendCert
metadata:
  annotations:
    meta.upbound.io/example-id: pki/v1beta1/secretbackendcert
  labels:
    testing.upbound.io/example-name: app
  name: app
spec:
  forProvider:
    backendSelector:
      matchLabels:
        testing.upbound.io/example-name: intermediate
    commonName: app.my.domain
    nameSelector:
      matchLabels:
        testing.upbound.io/example-name: test
