apiVersion: pki.vault.upbound.io/v1beta1
kind: SecretBackendConfigCA
metadata:
  annotations:
    meta.upbound.io/example-id: pki/v1beta1/secretbackendconfigca
  labels:
    testing.upbound.io/example-name: intermediate
  name: intermediate
spec:
  forProvider:
    backendSelector:
      matchLabels:
        testing.upbound.io/example-name: intermediate
    pemBundleSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
