apiVersion: pki.vault.upbound.io/v1beta1
kind: SecretBackendRole
metadata:
  annotations:
    meta.upbound.io/example-id: pki/v1beta1/secretbackendrole
  labels:
    testing.upbound.io/example-name: role
  name: role
spec:
  forProvider:
    allowIpSans: true
    allowSubdomains: true
    allowedDomains:
    - example.com
    - my.domain
    backendSelector:
      matchLabels:
        testing.upbound.io/example-name: pki
    keyBits: 4096
    keyType: rsa
    name: my_role
    ttl: 3600

---

apiVersion: vault.vault.upbound.io/v1beta1
kind: Mount
metadata:
  annotations:
    meta.upbound.io/example-id: pki/v1beta1/secretbackendrole
  labels:
    testing.upbound.io/example-name: pki
  name: pki
spec:
  forProvider:
    defaultLeaseTtlSeconds: 3600
    maxLeaseTtlSeconds: 86400
    path: pki
    type: pki
