apiVersion: pki.vault.upbound.io/v1beta1
kind: SecretBackendIntermediateCertRequest
metadata:
  annotations:
    meta.upbound.io/example-id: pki/v1beta1/secretbackendintermediatecertrequest
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    backendSelector:
      matchLabels:
        testing.upbound.io/example-name: pki
    commonName: app.my.domain
    type: internal
