apiVersion: pki.vault.upbound.io/v1beta1
kind: SecretBackendConfigUrls
metadata:
  annotations:
    meta.upbound.io/example-id: pki/v1beta1/secretbackendconfigurls
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    backendSelector:
      matchLabels:
        testing.upbound.io/example-name: root
    issuingCertificates:
    - http://127.0.0.1:8200/v1/pki/ca

---

apiVersion: vault.vault.upbound.io/v1beta1
kind: Mount
metadata:
  annotations:
    meta.upbound.io/example-id: pki/v1beta1/secretbackendconfigurls
  labels:
    testing.upbound.io/example-name: root
  name: root
spec:
  forProvider:
    defaultLeaseTtlSeconds: 8640000
    description: root PKI
    maxLeaseTtlSeconds: 8640000
    path: pki-root
    type: pki
