apiVersion: pki.vault.upbound.io/v1beta1
kind: SecretBackendRootCert
metadata:
  annotations:
    meta.upbound.io/example-id: pki/v1beta1/secretbackendrootcert
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    backendSelector:
      matchLabels:
        testing.upbound.io/example-name: pki
    commonName: Root CA
    excludeCnFromSans: true
    format: pem
    keyBits: 4096
    keyType: rsa
    organization: My organization
    ou: My OU
    privateKeyFormat: der
    ttl: "315360000"
    type: internal
