apiVersion: pki.vault.upbound.io/v1beta1
kind: SecretBackendIntermediateSetSigned
metadata:
  annotations:
    meta.upbound.io/example-id: pki/v1beta1/secretbackendintermediatesetsigned
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    backendSelector:
      matchLabels:
        testing.upbound.io/example-name: intermediate
    certificateSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: vault.vault.upbound.io/v1beta1
kind: Mount
metadata:
  annotations:
    meta.upbound.io/example-id: pki/v1beta1/secretbackendintermediatesetsigned
  labels:
    testing.upbound.io/example-name: intermediate
  name: intermediate
spec:
  forProvider:
    defaultLeaseTtlSeconds: 86400
    description: intermediate
    maxLeaseTtlSeconds: 86400
    path: pki-int
    type: pki

---

apiVersion: vault.vault.upbound.io/v1beta1
kind: Mount
metadata:
  annotations:
    meta.upbound.io/example-id: pki/v1beta1/secretbackendintermediatesetsigned
  labels:
    testing.upbound.io/example-name: root
  name: root
spec:
  forProvider:
    defaultLeaseTtlSeconds: 8640000
    description: root
    maxLeaseTtlSeconds: 8640000
    path: pki-root
    type: pki

---

apiVersion: pki.vault.upbound.io/v1beta1
kind: SecretBackendIntermediateCertRequest
metadata:
  annotations:
    meta.upbound.io/example-id: pki/v1beta1/secretbackendintermediatesetsigned
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    backendSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    commonName: SubOrg Intermediate CA
    type: internal

---

apiVersion: pki.vault.upbound.io/v1beta1
kind: SecretBackendRootCert
metadata:
  annotations:
    meta.upbound.io/example-id: pki/v1beta1/secretbackendintermediatesetsigned
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    backendSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    commonName: RootOrg Root CA
    country: US
    excludeCnFromSans: true
    format: pem
    keyBits: 4096
    keyType: rsa
    locality: San Francisco
    organization: RootOrg
    ou: Organizational Unit
    privateKeyFormat: der
    province: CA
    ttl: 86400
    type: internal
