apiVersion: identity.vault.upbound.io/v1alpha1
kind: GroupMemberEntityIds
metadata:
  annotations:
    meta.upbound.io/example-id: identity/v1alpha1/groupmemberentityids
  labels:
    testing.upbound.io/example-name: members
  name: members
spec:
  forProvider:
    exclusive: true
    groupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: internal
    memberEntityIds:
    - ${vault_identity_entity.user.id}

---

apiVersion: identity.vault.upbound.io/v1alpha1
kind: Entity
metadata:
  annotations:
    meta.upbound.io/example-id: identity/v1alpha1/groupmemberentityids
  labels:
    testing.upbound.io/example-name: user
  name: user
spec:
  forProvider:
    name: user

---

apiVersion: identity.vault.upbound.io/v1alpha1
kind: Group
metadata:
  annotations:
    meta.upbound.io/example-id: identity/v1alpha1/groupmemberentityids
  labels:
    testing.upbound.io/example-name: internal
  name: internal
spec:
  forProvider:
    externalMemberEntityIds: true
    metadata:
      version: "2"
    name: internal
    type: internal
