apiVersion: azure.vault.upbound.io/v1beta1
kind: SecretBackend
metadata:
  annotations:
    meta.upbound.io/example-id: azure/v1beta1/secretbackend
  labels:
    testing.upbound.io/example-name: azure
  name: azure
spec:
  forProvider:
    clientIdSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    identityTokenAudience: <TOKEN_AUDIENCE>
    identityTokenTtl: <TOKEN_TTL>
    subscriptionIdSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    tenantIdSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
