apiVersion: managed.vault.upbound.io/v1alpha1
kind: Keys
metadata:
  annotations:
    meta.upbound.io/example-id: managed/v1alpha1/keys
  labels:
    testing.upbound.io/example-name: keys
  name: keys
spec:
  forProvider:
    aws:
    - accessKey: ${var.aws_access_key}
      keyBits: "2048"
      keyType: RSA
      kmsKey: alias/vault_aws_key_1
      name: aws-key-1
      secretKey: ${var.aws_secret_key}
    - accessKey: ${var.aws_access_key}
      keyBits: "4096"
      keyType: RSA
      kmsKey: alias/vault_aws_key_2
      name: aws-key-2
      secretKey: ${var.aws_secret_key}

---

apiVersion: vault.vault.upbound.io/v1alpha1
kind: Mount
metadata:
  annotations:
    meta.upbound.io/example-id: managed/v1alpha1/keys
  labels:
    testing.upbound.io/example-name: pki
  name: pki
spec:
  forProvider:
    allowedManagedKeys:
    - ${tolist(vault_managed_keys.keys.aws)[0].name}
    - ${tolist(vault_managed_keys.keys.aws)[1].name}
    defaultLeaseTtlSeconds: 3600
    description: Example mount for managed keys
    maxLeaseTtlSeconds: 36000
    path: pki
    type: pki
