apiVersion: password.vault.upbound.io/v1alpha1
kind: Policy
metadata:
  annotations:
    meta.upbound.io/example-id: password/v1alpha1/policy
  labels:
    testing.upbound.io/example-name: alphanumeric
  name: alphanumeric
spec:
  forProvider:
    name: alphanumeric
    policy: |2
          length = 20
          rule "charset" {
            charset = "abcdefghijklmnopqrstuvwxyz0123456789"
          }
