apiVersion: kmip.vault.upbound.io/v1alpha1
kind: SecretScope
metadata:
  annotations:
    meta.upbound.io/example-id: kmip/v1alpha1/secretscope
  labels:
    testing.upbound.io/example-name: dev
  name: dev
spec:
  forProvider:
    force: true
    pathSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    scope: dev

---

apiVersion: kmip.vault.upbound.io/v1alpha1
kind: SecretBackend
metadata:
  annotations:
    meta.upbound.io/example-id: kmip/v1alpha1/secretscope
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    description: Vault KMIP backend
    path: kmip
