apiVersion: azure.vault.upbound.io/v1alpha1
kind: SecretBackendRole
metadata:
  annotations:
    meta.upbound.io/example-id: azure/v1alpha1/secretbackendrole
  labels:
    testing.upbound.io/example-name: generated_role
  name: generated-role
spec:
  forProvider:
    azureRoles:
    - roleName: Reader
      scope: /subscriptions/${var.subscription_id}/resourceGroups/azure-vault-group
    backend: ${vault_azure_secret_backend.azure.path}
    maxTtl: 600
    role: generated_role
    signInAudience: AzureADMyOrg
    tags:
    - team:engineering
    - environment:development
    ttl: 300

---

apiVersion: azure.vault.upbound.io/v1alpha1
kind: SecretBackend
metadata:
  annotations:
    meta.upbound.io/example-id: azure/v1alpha1/secretbackendrole
  labels:
    testing.upbound.io/example-name: azure
  name: azure
spec:
  forProvider:
    clientIdSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    clientSecretSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    subscriptionIdSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    tenantIdSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
