apiVersion: ssh.vault.upbound.io/v1alpha1
kind: SecretBackendCA
metadata:
  annotations:
    meta.upbound.io/example-id: ssh/v1alpha1/secretbackendca
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    backendSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: vault.vault.upbound.io/v1alpha1
kind: Mount
metadata:
  annotations:
    meta.upbound.io/example-id: ssh/v1alpha1/secretbackendca
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    type: ssh
