apiVersion: jwt.vault.upbound.io/v1alpha1
kind: AuthBackendRole
metadata:
  annotations:
    meta.upbound.io/example-id: jwt/v1alpha1/authbackendrole
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    backendSelector:
      matchLabels:
        testing.upbound.io/example-name: jwt
    boundAudiences:
    - https://myco.test
    boundClaims:
      color: red,green,blue
    roleName: test-role
    roleType: jwt
    tokenPolicies:
    - default
    - dev
    - prod
    userClaim: https://vault/user

---

apiVersion: jwt.vault.upbound.io/v1alpha1
kind: AuthBackend
metadata:
  annotations:
    meta.upbound.io/example-id: jwt/v1alpha1/authbackendrole
  labels:
    testing.upbound.io/example-name: jwt
  name: jwt
spec:
  forProvider:
    path: jwt
