apiVersion: terraform.vault.upbound.io/v1beta1
kind: CloudSecretRole
metadata:
  annotations:
    meta.upbound.io/example-id: terraform/v1beta1/cloudsecretrole
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    backendSelector:
      matchLabels:
        testing.upbound.io/example-name: test
    name: test-role
    organization: example-organization-name
    teamId: team-ieF4isC...

---

apiVersion: terraform.vault.upbound.io/v1beta1
kind: CloudSecretBackend
metadata:
  annotations:
    meta.upbound.io/example-id: terraform/v1beta1/cloudsecretrole
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    backend: terraform
    description: Manages the Terraform Cloud backend
    tokenSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
