apiVersion: terraform.vault.upbound.io/v1beta1
kind: CloudSecretBackend
metadata:
  annotations:
    meta.upbound.io/example-id: terraform/v1beta1/cloudsecretbackend
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    backend: terraform
    description: Manages the Terraform Cloud backend
    tokenSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
