apiVersion: alicloud.vault.upbound.io/v1beta1
kind: AuthBackendRole
metadata:
  annotations:
    meta.upbound.io/example-id: alicloud/v1beta1/authbackendrole
  labels:
    testing.upbound.io/example-name: alicloud
  name: alicloud
spec:
  forProvider:
    arn: acs:ram:123456:tf:role/foobar
    backendSelector:
      matchLabels:
        testing.upbound.io/example-name: alicloud
    role: example

---

apiVersion: auth.vault.upbound.io/v1beta1
kind: Backend
metadata:
  annotations:
    meta.upbound.io/example-id: alicloud/v1beta1/authbackendrole
  labels:
    testing.upbound.io/example-name: alicloud
  name: alicloud
spec:
  forProvider:
    path: alicloud
    type: alicloud
