/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *SecretBackendCert) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SecretBackendConfigCA) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SecretBackendConfigUrls) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SecretBackendCrlConfig) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SecretBackendIntermediateCertRequest) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SecretBackendIntermediateSetSigned) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SecretBackendRole) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SecretBackendRootCert) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SecretBackendRootSignIntermediate) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SecretBackendSign) Hub() {}
