/*
Copyright 2022 Upbound Inc.
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	resource "github.com/crossplane/upjet/v2/pkg/resource"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this PinnedVersion.
func (mg *PinnedVersion) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Name),
		Extract:      resource.ExtractParamPath("name", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.NameRef,
		Selector:     mg.Spec.ForProvider.NameSelector,
		To: reference.To{
			List:    &PluginList{},
			Managed: &Plugin{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Name")
	}
	mg.Spec.ForProvider.Name = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.NameRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Type),
		Extract:      resource.ExtractParamPath("type", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.TypeRef,
		Selector:     mg.Spec.ForProvider.TypeSelector,
		To: reference.To{
			List:    &PluginList{},
			Managed: &Plugin{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Type")
	}
	mg.Spec.ForProvider.Type = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.TypeRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Version),
		Extract:      resource.ExtractParamPath("version", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.VersionRef,
		Selector:     mg.Spec.ForProvider.VersionSelector,
		To: reference.To{
			List:    &PluginList{},
			Managed: &Plugin{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Version")
	}
	mg.Spec.ForProvider.Version = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.VersionRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Name),
		Extract:      resource.ExtractParamPath("name", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.NameRef,
		Selector:     mg.Spec.InitProvider.NameSelector,
		To: reference.To{
			List:    &PluginList{},
			Managed: &Plugin{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Name")
	}
	mg.Spec.InitProvider.Name = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.NameRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Type),
		Extract:      resource.ExtractParamPath("type", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.TypeRef,
		Selector:     mg.Spec.InitProvider.TypeSelector,
		To: reference.To{
			List:    &PluginList{},
			Managed: &Plugin{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Type")
	}
	mg.Spec.InitProvider.Type = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.TypeRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Version),
		Extract:      resource.ExtractParamPath("version", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.VersionRef,
		Selector:     mg.Spec.InitProvider.VersionSelector,
		To: reference.To{
			List:    &PluginList{},
			Managed: &Plugin{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Version")
	}
	mg.Spec.InitProvider.Version = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.VersionRef = rsp.ResolvedReference

	return nil
}
