apiVersion: generic.vault.upbound.io/v1beta1
kind: Secret
metadata:
  annotations:
    meta.upbound.io/example-id: generic/v1beta1/secret
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    dataJsonSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    path: secret/foo
