apiVersion: rabbitmq.vault.upbound.io/v1beta1
kind: SecretBackendRole
metadata:
  annotations:
    meta.upbound.io/example-id: rabbitmq/v1beta1/secretbackendrole
  labels:
    testing.upbound.io/example-name: role
  name: role
spec:
  forProvider:
    backendSelector:
      matchLabels:
        testing.upbound.io/example-name: rabbitmq
    name: deploy
    tags: tag1,tag2
    vhost:
    - configure: ""
      host: /
      read: .*
      write: ""
    vhostTopic:
    - host: /
      vhost:
      - read: .*
        topic: amq.topic
        write: ""

---

apiVersion: rabbitmq.vault.upbound.io/v1beta1
kind: SecretBackend
metadata:
  annotations:
    meta.upbound.io/example-id: rabbitmq/v1beta1/secretbackendrole
  labels:
    testing.upbound.io/example-name: rabbitmq
  name: rabbitmq
spec:
  forProvider:
    connectionUri: https://.....
    passwordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    usernameSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
