apiVersion: identity.vault.upbound.io/v1beta1
kind: OidcProvider
metadata:
  annotations:
    meta.upbound.io/example-id: identity/v1beta1/oidcprovider
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    allowedClientIds:
    - ${vault_identity_oidc_client.test.client_id}
    httpsEnabled: false
    issuerHost: 127.0.0.1:8200
    name: my-provider
    scopesSupported:
    - ${vault_identity_oidc_scope.test.name}

---

apiVersion: identity.vault.upbound.io/v1beta1
kind: OidcAssignment
metadata:
  annotations:
    meta.upbound.io/example-id: identity/v1beta1/oidcprovider
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    entityIds:
    - fake-ascbascas-2231a-sdfaa
    groupIds:
    - fake-sajkdsad-32414-sfsada
    name: my-assignment

---

apiVersion: identity.vault.upbound.io/v1beta1
kind: OidcClient
metadata:
  annotations:
    meta.upbound.io/example-id: identity/v1beta1/oidcprovider
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    accessTokenTtl: 7200
    assignments:
    - ${vault_identity_oidc_assignment.test.name}
    idTokenTtl: 2400
    key: my-key
    name: application
    redirectUris:
    - http://127.0.0.1:9200/v1/auth-methods/oidc:authenticate:callback
    - http://127.0.0.1:8251/callback
    - http://127.0.0.1:8080/callback

---

apiVersion: identity.vault.upbound.io/v1beta1
kind: OidcKey
metadata:
  annotations:
    meta.upbound.io/example-id: identity/v1beta1/oidcprovider
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    allowedClientIds:
    - '*'
    name: my-key
    rotationPeriod: 3600
    verificationTtl: 3600

---

apiVersion: identity.vault.upbound.io/v1beta1
kind: OidcScope
metadata:
  annotations:
    meta.upbound.io/example-id: identity/v1beta1/oidcprovider
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    description: Groups scope.
    name: groups
    template: |-
      ${jsonencode(
        {
          groups = "{{identity.entity.groups.names}}",
        }
        )}
