apiVersion: identity.vault.upbound.io/v1beta1
kind: OidcKey
metadata:
  annotations:
    meta.upbound.io/example-id: identity/v1beta1/oidckey
  labels:
    testing.upbound.io/example-name: key
  name: key
spec:
  forProvider:
    algorithm: RS256
    name: key

---

apiVersion: identity.vault.upbound.io/v1beta1
kind: OidcKeyAllowedClientID
metadata:
  annotations:
    meta.upbound.io/example-id: identity/v1beta1/oidckey
  labels:
    testing.upbound.io/example-name: role
  name: role
spec:
  forProvider:
    allowedClientIdSelector:
      matchLabels:
        testing.upbound.io/example-name: role
    keyNameSelector:
      matchLabels:
        testing.upbound.io/example-name: key

---

apiVersion: identity.vault.upbound.io/v1beta1
kind: OidcRole
metadata:
  annotations:
    meta.upbound.io/example-id: identity/v1beta1/oidckey
  labels:
    testing.upbound.io/example-name: role
  name: role
spec:
  forProvider:
    keySelector:
      matchLabels:
        testing.upbound.io/example-name: key
    name: role
