apiVersion: approle.vault.upbound.io/v1alpha1
kind: AuthBackendLogin
metadata:
  annotations:
    meta.upbound.io/example-id: approle/v1alpha1/authbackendlogin
  labels:
    testing.upbound.io/example-name: login
  name: login
spec:
  forProvider:
    backend: cert
    roleId: ${vault_approle_auth_backend_role.example.role_id}
    secretId: ${vault_approle_auth_backend_role_secret_id.id.secret_id}

---

apiVersion: approle.vault.upbound.io/v1alpha1
kind: AuthBackendRole
metadata:
  annotations:
    meta.upbound.io/example-id: approle/v1alpha1/authbackendlogin
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    backend: ${vault_auth_backend.approle.path}
    roleName: test-role
    tokenPolicies:
    - default
    - dev
    - prod

---

apiVersion: auth.vault.upbound.io/v1alpha1
kind: Backend
metadata:
  annotations:
    meta.upbound.io/example-id: approle/v1alpha1/authbackendlogin
  labels:
    testing.upbound.io/example-name: approle
  name: approle
spec:
  forProvider:
    type: approle

---

