apiVersion: vault.vault.upbound.io/v1alpha1
kind: Token
metadata:
  annotations:
    meta.upbound.io/example-id: vault/v1alpha1/token
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    metadata:
      purpose: service-account
    policies:
    - policy1
    - policy2
    renewIncrement: 86400
    renewMinLease: 43200
    renewable: true
    roleName: app
    ttl: 24h
