apiVersion: kv.vault.upbound.io/v1beta1
kind: Secret
metadata:
  annotations:
    meta.upbound.io/example-id: kv/v1beta1/secret
  labels:
    testing.upbound.io/example-name: secret
  name: secret
spec:
  forProvider:
    dataJsonSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    path: dummy

---

apiVersion: vault.vault.upbound.io/v1beta1
kind: Mount
metadata:
  annotations:
    meta.upbound.io/example-id: kv/v1beta1/secret
  labels:
    testing.upbound.io/example-name: kvv1
  name: kvv1
spec:
  forProvider:
    description: KV Version 1 secret engine mount
    options:
      version: "1"
    path: kvv1
    type: kv
