apiVersion: kv.vault.upbound.io/v1beta1
kind: SecretV2
metadata:
  annotations:
    meta.upbound.io/example-id: kv/v1beta1/secretv2
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    cas: 1
    customMetadata:
    - data:
        bar: "12345"
        foo: vault@example.com
      maxVersions: 5
    dataJsonSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    deleteAllVersions: true
    mountSelector:
      matchLabels:
        testing.upbound.io/example-name: kvv2
    name: secret

---

apiVersion: vault.vault.upbound.io/v1beta1
kind: Mount
metadata:
  annotations:
    meta.upbound.io/example-id: kv/v1beta1/secretv2
  labels:
    testing.upbound.io/example-name: kvv2
  name: kvv2
spec:
  forProvider:
    description: KV Version 2 secret engine mount
    options:
      version: "2"
    path: kvv2
    type: kv
