/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Entity) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *EntityAlias) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *EntityPolicies) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Group) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *GroupAlias) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *GroupMemberEntityIds) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *GroupMemberGroupIds) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *GroupPolicies) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MfaDuo) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MfaLoginEnforcement) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MfaOkta) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MfaPingid) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MfaTotp) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Oidc) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *OidcAssignment) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *OidcClient) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *OidcKey) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *OidcKeyAllowedClientID) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *OidcProvider) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *OidcRole) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *OidcScope) Hub() {}
