apiVersion: identity.vault.m.upbound.io/v1alpha1
kind: OidcProvider
metadata:
  annotations:
    meta.upbound.io/example-id: identity/v1alpha1/oidcprovider
  labels:
    testing.upbound.io/example-name: test
  name: test
  namespace: upbound-system
spec:
  forProvider:
    allowedClientIdsRefs:
    - name: test
    httpsEnabled: false
    issuerHost: 127.0.0.1:8200
    name: my-provider
    scopesSupportedRefs:
    - name: test

---

apiVersion: identity.vault.m.upbound.io/v1alpha1
kind: OidcAssignment
metadata:
  annotations:
    meta.upbound.io/example-id: identity/v1alpha1/oidcprovider
  labels:
    testing.upbound.io/example-name: test
  name: test
  namespace: upbound-system
spec:
  forProvider:
    entityIdsRefs:
    - name: example
    groupIdsRefs:
    - name: example
    name: my-assignment

---

apiVersion: identity.vault.m.upbound.io/v1alpha1
kind: OidcClient
metadata:
  annotations:
    meta.upbound.io/example-id: identity/v1alpha1/oidcprovider
  labels:
    testing.upbound.io/example-name: test
  name: test
  namespace: upbound-system
spec:
  forProvider:
    accessTokenTtl: 7200
    assignmentsRefs:
    - name: test
    idTokenTtl: 2400
    key: my-key
    name: application
    redirectUris:
    - http://127.0.0.1:9200/v1/auth-methods/oidc:authenticate:callback
    - http://127.0.0.1:8251/callback
    - http://127.0.0.1:8080/callback

---

apiVersion: identity.vault.m.upbound.io/v1alpha1
kind: OidcKey
metadata:
  annotations:
    meta.upbound.io/example-id: identity/v1alpha1/oidcprovider
  labels:
    testing.upbound.io/example-name: test
  name: test
  namespace: upbound-system
spec:
  forProvider:
    allowedClientIds:
    - '*'
    name: my-key
    rotationPeriod: 3600
    verificationTtl: 3600

---

apiVersion: identity.vault.m.upbound.io/v1alpha1
kind: OidcScope
metadata:
  annotations:
    meta.upbound.io/example-id: identity/v1alpha1/oidcprovider
  labels:
    testing.upbound.io/example-name: test
  name: test
  namespace: upbound-system
spec:
  forProvider:
    description: Groups scope.
    name: groups
    template: |-
      ${jsonencode(
        {
          groups = "{{identity.entity.groups.names}}",
        }
        )}
