apiVersion: database.vault.upbound.io/v1beta1
kind: SecretsMount
metadata:
  annotations:
    meta.upbound.io/example-id: database/v1beta1/secretsmount
  labels:
    testing.upbound.io/example-name: db
  name: db
spec:
  forProvider:
    mssql:
    - allowedRoles:
      - dev1
      connectionUrl: sqlserver://{{username}}:{{password}}@127.0.0.1:1433
      name: db1
      passwordSecretRef:
        key: example-key
        name: example-secret
        namespace: upbound-system
      username: sa
    path: db
    postgresql:
    - allowedRoles:
      - dev2
      connectionUrl: postgresql://{{username}}:{{password}}@127.0.0.1:5432/postgres
      name: db2
      passwordSecretRef:
        key: example-key
        name: example-secret
        namespace: upbound-system
      username: postgres
      verifyConnection: true

---

apiVersion: database.vault.upbound.io/v1beta1
kind: SecretBackendRole
metadata:
  annotations:
    meta.upbound.io/example-id: database/v1beta1/secretsmount
  labels:
    testing.upbound.io/example-name: dev1
  name: dev1
spec:
  forProvider:
    backendSelector:
      matchLabels:
        testing.upbound.io/example-name: db
    creationStatements:
    - CREATE LOGIN [{{name}}] WITH PASSWORD = '{{password}}';
    - CREATE USER [{{name}}] FOR LOGIN [{{name}}];
    - GRANT SELECT ON SCHEMA::dbo TO [{{name}}];
    dbNameSelector:
      matchLabels:
        testing.upbound.io/example-name: db
    name: dev1

---

apiVersion: database.vault.upbound.io/v1beta1
kind: SecretBackendRole
metadata:
  annotations:
    meta.upbound.io/example-id: database/v1beta1/secretsmount
  labels:
    testing.upbound.io/example-name: dev2
  name: dev2
spec:
  forProvider:
    backendSelector:
      matchLabels:
        testing.upbound.io/example-name: db
    creationStatements:
    - CREATE ROLE "{{name}}" WITH LOGIN PASSWORD '{{password}}' VALID UNTIL '{{expiration}}';
    - GRANT SELECT ON ALL TABLES IN SCHEMA public TO "{{name}}";
    dbNameSelector:
      matchLabels:
        testing.upbound.io/example-name: db
    name: dev2
