apiVersion: kmip.vault.upbound.io/v1alpha1
kind: SecretBackend
metadata:
  annotations:
    meta.upbound.io/example-id: kmip/v1alpha1/secretbackend
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    defaultTlsClientKeyBits: 4096
    defaultTlsClientKeyType: rsa
    defaultTlsClientTtl: 86400
    description: Vault KMIP backend
    listenAddrs:
    - 127.0.0.1:5696
    - 127.0.0.1:8080
    path: kmip
    tlsCaKeyBits: 4096
    tlsCaKeyType: rsa
