apiVersion: mongodbatlas.vault.upbound.io/v1beta1
kind: SecretBackend
metadata:
  annotations:
    meta.upbound.io/example-id: mongodbatlas/v1beta1/secretbackend
  labels:
    testing.upbound.io/example-name: config
  name: config
spec:
  forProvider:
    mountSelector:
      matchLabels:
        testing.upbound.io/example-name: mongo
    privateKey: privateKey
    publicKey: publicKey

---

apiVersion: vault.vault.upbound.io/v1beta1
kind: Mount
metadata:
  annotations:
    meta.upbound.io/example-id: mongodbatlas/v1beta1/secretbackend
  labels:
    testing.upbound.io/example-name: mongo
  name: mongo
spec:
  forProvider:
    description: MongoDB Atlas secret engine mount
    path: mongodbatlas
    type: mongodbatlas
