apiVersion: mongodbatlas.vault.upbound.io/v1beta1
kind: SecretRole
metadata:
  annotations:
    meta.upbound.io/example-id: mongodbatlas/v1beta1/secretrole
  labels:
    testing.upbound.io/example-name: role
  name: role
spec:
  forProvider:
    cidrBlocks: 192.168.1.3/35
    ipAddresses: 192.168.1.5, 192.168.1.6
    maxTtl: "120"
    mountSelector:
      matchLabels:
        testing.upbound.io/example-name: mongo
    name: tf-test-role
    organizationId: 7cf5a45a9ccf6400e60981b7
    projectId: 5cf5a45a9ccf6400e60981b6
    projectRoles:
    - GROUP_READ_ONLY
    roles:
    - ORG_READ_ONLY
    ttl: "60"

---

apiVersion: mongodbatlas.vault.upbound.io/v1beta1
kind: SecretBackend
metadata:
  annotations:
    meta.upbound.io/example-id: mongodbatlas/v1beta1/secretrole
  labels:
    testing.upbound.io/example-name: config
  name: config
spec:
  forProvider:
    mountSelector:
      matchLabels:
        testing.upbound.io/example-name: mongo
    privateKey: privateKey
    publicKey: publicKey

---

apiVersion: vault.vault.upbound.io/v1beta1
kind: Mount
metadata:
  annotations:
    meta.upbound.io/example-id: mongodbatlas/v1beta1/secretrole
  labels:
    testing.upbound.io/example-name: mongo
  name: mongo
spec:
  forProvider:
    description: MongoDB Atlas secret engine mount
    path: '%s'
    type: mongodbatlas
