apiVersion: kubernetes.vault.upbound.io/v1beta1
kind: SecretBackend
metadata:
  annotations:
    meta.upbound.io/example-id: kubernetes/v1beta1/secretbackend
  labels:
    testing.upbound.io/example-name: config
  name: config
spec:
  forProvider:
    defaultLeaseTtlSeconds: 43200
    description: kubernetes secrets engine description
    disableLocalCaJwt: false
    kubernetesCaCert: ${file("/path/to/cert")}
    kubernetesHost: https://127.0.0.1:61233
    maxLeaseTtlSeconds: 86400
    path: kubernetes
    serviceAccountJwtSecretRef:
      key: attribute.token
      name: example-secret
      namespace: upbound-system
