apiVersion: kubernetes.vault.upbound.io/v1alpha1
kind: SecretBackendRole
metadata:
  annotations:
    meta.upbound.io/example-id: kubernetes/v1alpha1/secretbackendrole
  labels:
    testing.upbound.io/example-name: sa-example
  name: sa-example
spec:
  forProvider:
    allowedKubernetesNamespaces:
    - '*'
    backendSelector:
      matchLabels:
        testing.upbound.io/example-name: config
    extraAnnotations:
      env: development
      location: earth
    extraLabels:
      id: abc123
      name: some_name
    name: service-account-name-role
    serviceAccountName: test-service-account-with-generated-token
    tokenDefaultTtl: 21600
    tokenMaxTtl: 43200
