apiVersion: nomad.vault.upbound.io/v1alpha1
kind: SecretRole
metadata:
  annotations:
    meta.upbound.io/example-id: nomad/v1alpha1/secretrole
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    backendSelector:
      matchLabels:
        testing.upbound.io/example-name: config
    policies:
    - readonly
    role: test
    type: client

---

apiVersion: nomad.vault.upbound.io/v1alpha1
kind: SecretBackend
metadata:
  annotations:
    meta.upbound.io/example-id: nomad/v1alpha1/secretrole
  labels:
    testing.upbound.io/example-name: config
  name: config
spec:
  forProvider:
    address: https://127.0.0.1:4646
    backend: nomad
    defaultLeaseTtlSeconds: "3600"
    description: test description
    maxLeaseTtlSeconds: "7200"
    tokenSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
