apiVersion: aws.vault.upbound.io/v1alpha1
kind: SecretBackendRole
metadata:
  annotations:
    meta.upbound.io/example-id: aws/v1alpha1/secretbackendrole
  labels:
    testing.upbound.io/example-name: role
  name: role
spec:
  forProvider:
    backendSelector:
      matchLabels:
        testing.upbound.io/example-name: aws
    credentialType: iam_user
    name: deploy
    policyDocument: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": "iam:*",
            "Resource": "*"
          }
        ]
      }

---

apiVersion: aws.vault.upbound.io/v1alpha1
kind: SecretBackend
metadata:
  annotations:
    meta.upbound.io/example-id: aws/v1alpha1/secretbackendrole
  labels:
    testing.upbound.io/example-name: aws
  name: aws
spec:
  forProvider:
    accessKeySecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    secretKeySecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
