apiVersion: kmip.vault.upbound.io/v1beta1
kind: SecretRole
metadata:
  annotations:
    meta.upbound.io/example-id: kmip/v1beta1/secretrole
  labels:
    testing.upbound.io/example-name: admin
  name: admin
spec:
  forProvider:
    operationActivate: true
    operationCreate: true
    operationDestroy: true
    operationGet: true
    operationGetAttributes: true
    pathSelector:
      matchLabels:
        testing.upbound.io/example-name: dev
    role: admin
    scopeSelector:
      matchLabels:
        testing.upbound.io/example-name: dev
    tlsClientKeyBits: 256
    tlsClientKeyType: ec

---

apiVersion: kmip.vault.upbound.io/v1beta1
kind: SecretBackend
metadata:
  annotations:
    meta.upbound.io/example-id: kmip/v1beta1/secretrole
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    description: Vault KMIP backend
    path: kmip

---

apiVersion: kmip.vault.upbound.io/v1beta1
kind: SecretScope
metadata:
  annotations:
    meta.upbound.io/example-id: kmip/v1beta1/secretrole
  labels:
    testing.upbound.io/example-name: dev
  name: dev
spec:
  forProvider:
    force: true
    pathSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    scope: dev
