apiVersion: aws.vault.upbound.io/v1beta1
kind: AuthBackendCert
metadata:
  annotations:
    meta.upbound.io/example-id: aws/v1beta1/authbackendcert
  labels:
    testing.upbound.io/example-name: cert
  name: cert
spec:
  forProvider:
    backendSelector:
      matchLabels:
        testing.upbound.io/example-name: aws

---

apiVersion: auth.vault.upbound.io/v1beta1
kind: Backend
metadata:
  annotations:
    meta.upbound.io/example-id: aws/v1beta1/authbackendcert
  labels:
    testing.upbound.io/example-name: aws
  name: aws
spec:
  forProvider:
    type: aws
